
package vista;

import controlador.ControllerEstudiante;
import javax.swing.JFrame;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author root
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFinal
     */
    public Principal() {
        
        initComponents();
        
        /*agregaremos una serie de propiedades que nos permitiran configurar la ventana Jframe*/
        
        /*nos permitira maximizar la ventana JFrame*/
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        /*esta linea de codigo nos permitira terminar todos los procesos del proyecto cuando salgamos del mismo*/
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        /*este metodo nos permitira centrar la ventana JFrame*/
        this.setLocationRelativeTo(null);
        
        /*creamos un objeto de tipo TableColum el cual nos permitira configurar el JTable
        como por ejemplo cambiar o redimenzionar las columnas*/
        
        
        TableColumnModel columnModel = tableDatos.getColumnModel();
        
        /*obtenemos el ancho del JTable*/
        int longitudTabla = columnModel.getTotalColumnWidth();
        
        /*agregamos las respectivas dimensiones a las columnas
        los hacemos a traves de porcetaje por lo tanto debemos tener en cuenta la formula
        (longitudTabla*porcenteje)/100*/        
        columnModel.getColumn(0).setPreferredWidth((longitudTabla*10)/100);
        columnModel.getColumn(1).setPreferredWidth((longitudTabla*20)/100);
        columnModel.getColumn(2).setPreferredWidth((longitudTabla*30)/100);
        columnModel.getColumn(3).setPreferredWidth((longitudTabla*20)/100);
        columnModel.getColumn(4).setPreferredWidth((longitudTabla*20)/100);
        
        /*Conectamos la clase controlador con la interfaz grafica por lo tanto debemos 
        crear un objeto de tipo ControllerEstudiante, le pasamos como parametro la interfaz grafica
        solo bastaria con escribir la palabra clave this*/        
        ControllerEstudiante controlador = new ControllerEstudiante(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        barraDesplazamiento = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelMenu = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelFormulario = new javax.swing.JPanel();
        panelRegistroEstudiante = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        labelTipoDoc = new javax.swing.JLabel();
        comboBoxTipoDocumento = new javax.swing.JComboBox<>();
        labelNumDoc = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrarEstudiante = new javax.swing.JButton();
        btnLimpiarEstudiante = new javax.swing.JButton();
        btnActualizarEstudiante = new javax.swing.JButton();
        labelGenero = new javax.swing.JLabel();
        comboBoxGenero = new javax.swing.JComboBox<>();
        panelListadoEstudiante = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDatos = new javax.swing.JTable();
        btnActualizarTablaFormularioRegistro = new javax.swing.JButton();
        panelConsulta = new javax.swing.JPanel();
        panelBusqueda = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxTipoBusqueda = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        textBusqueda = new javax.swing.JTextField();
        btnBuscarConsulta = new javax.swing.JButton();
        panelListadoBusqueda = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBusqueda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrarView = new javax.swing.JButton();
        btnActualizarView = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setLayout(new java.awt.GridBagLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resizedPhoto.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelInicio.add(jLabel2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Control De Estudiantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelInicio.add(jLabel1, gridBagConstraints);

        panelMenu.addTab("Inicio", panelInicio);

        panelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        panelFormulario.setLayout(new java.awt.GridBagLayout());

        panelRegistroEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fomulario De Registro", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panelRegistroEstudiante.setPreferredSize(new java.awt.Dimension(800, 362));
        panelRegistroEstudiante.setLayout(new java.awt.GridBagLayout());

        labelCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelCodigo.setText("Código: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelRegistroEstudiante.add(labelCodigo, gridBagConstraints);

        txtCodigo.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        panelRegistroEstudiante.add(txtCodigo, gridBagConstraints);

        labelTipoDoc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTipoDoc.setText("Tipo Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelRegistroEstudiante.add(labelTipoDoc, gridBagConstraints);

        comboBoxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula de Identidad", "Cédula de Extranjeria" }));
        comboBoxTipoDocumento.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        panelRegistroEstudiante.add(comboBoxTipoDocumento, gridBagConstraints);

        labelNumDoc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNumDoc.setText("Número Documento: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        panelRegistroEstudiante.add(labelNumDoc, gridBagConstraints);

        txtNumDoc.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        panelRegistroEstudiante.add(txtNumDoc, gridBagConstraints);

        labelName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelName.setText("Nombres: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelRegistroEstudiante.add(labelName, gridBagConstraints);

        txtNombre.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        panelRegistroEstudiante.add(txtNombre, gridBagConstraints);

        labelLastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelLastName.setText("Apellidos: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        panelRegistroEstudiante.add(labelLastName, gridBagConstraints);

        txtApellido.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        panelRegistroEstudiante.add(txtApellido, gridBagConstraints);

        labelDireccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelDireccion.setText("Direccion: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelRegistroEstudiante.add(labelDireccion, gridBagConstraints);

        txtDireccion.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        panelRegistroEstudiante.add(txtDireccion, gridBagConstraints);

        labelTelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTelefono.setText("Telefono: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        panelRegistroEstudiante.add(labelTelefono, gridBagConstraints);

        txtTelefono.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        panelRegistroEstudiante.add(txtTelefono, gridBagConstraints);

        jPanel1.setPreferredSize(new java.awt.Dimension(723, 50));

        btnRegistrarEstudiante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png"))); // NOI18N
        btnRegistrarEstudiante.setText("Registrar");
        btnRegistrarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnRegistrarEstudiante);

        btnLimpiarEstudiante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimpiarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clean.png"))); // NOI18N
        btnLimpiarEstudiante.setText("Limpiar");
        btnLimpiarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnLimpiarEstudiante);

        btnActualizarEstudiante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnActualizarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        btnActualizarEstudiante.setText("Actualizar");
        btnActualizarEstudiante.setEnabled(false);
        btnActualizarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnActualizarEstudiante);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelRegistroEstudiante.add(jPanel1, gridBagConstraints);

        labelGenero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelGenero.setText("Genero: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelRegistroEstudiante.add(labelGenero, gridBagConstraints);

        comboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        comboBoxGenero.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        panelRegistroEstudiante.add(comboBoxGenero, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelFormulario.add(panelRegistroEstudiante, gridBagConstraints);

        panelListadoEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Listado Estudiantes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panelListadoEstudiante.setPreferredSize(new java.awt.Dimension(800, 362));
        panelListadoEstudiante.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Listado Registros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelListadoEstudiante.add(jLabel4, gridBagConstraints);

        jScrollPane2.setName(""); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(453, 260));
        jScrollPane2.setRequestFocusEnabled(false);

        tableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Telefono", "Genero"
            }
        ));
        jScrollPane2.setViewportView(tableDatos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 30);
        panelListadoEstudiante.add(jScrollPane2, gridBagConstraints);

        btnActualizarTablaFormularioRegistro.setText("Actualizar Tabla");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 30);
        panelListadoEstudiante.add(btnActualizarTablaFormularioRegistro, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelFormulario.add(panelListadoEstudiante, gridBagConstraints);

        panelMenu.addTab("Formulario Estudiante", panelFormulario);

        panelConsulta.setBackground(new java.awt.Color(255, 255, 255));
        panelConsulta.setLayout(new java.awt.GridBagLayout());

        panelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fomulario De Consulta", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panelBusqueda.setPreferredSize(new java.awt.Dimension(800, 222));
        panelBusqueda.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Control Estudiantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        panelBusqueda.add(jLabel3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Buscar Por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        panelBusqueda.add(jLabel5, gridBagConstraints);

        comboBoxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Número Documento", "Nombre/Apellido", "Genero" }));
        comboBoxTipoBusqueda.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        panelBusqueda.add(comboBoxTipoBusqueda, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Busqueda: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        panelBusqueda.add(jLabel6, gridBagConstraints);

        textBusqueda.setPreferredSize(new java.awt.Dimension(190, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        panelBusqueda.add(textBusqueda, gridBagConstraints);

        btnBuscarConsulta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarConsulta.setText("Buscar Datos");
        btnBuscarConsulta.setToolTipText("");
        btnBuscarConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        panelBusqueda.add(btnBuscarConsulta, gridBagConstraints);

        panelConsulta.add(panelBusqueda, new java.awt.GridBagConstraints());

        panelListadoBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Resultados", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panelListadoBusqueda.setPreferredSize(new java.awt.Dimension(800, 492));
        panelListadoBusqueda.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Listado Estudiantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelListadoBusqueda.add(jLabel7, gridBagConstraints);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(683, 303));

        tableBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Genero", "Telefono"
            }
        ));
        jScrollPane3.setViewportView(tableBusqueda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 50);
        panelListadoBusqueda.add(jScrollPane3, gridBagConstraints);

        jPanel2.setName(""); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 50));

        btnRegistrarView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrarView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png"))); // NOI18N
        btnRegistrarView.setText("Registrar");
        btnRegistrarView.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(btnRegistrarView);

        btnActualizarView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnActualizarView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        btnActualizarView.setText("Actualizar");
        btnActualizarView.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(btnActualizarView);

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(btnEliminar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 50);
        panelListadoBusqueda.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelConsulta.add(panelListadoBusqueda, gridBagConstraints);

        panelMenu.addTab("Consultas", panelConsulta);

        panelPrincipal.add(panelMenu, java.awt.BorderLayout.CENTER);

        barraDesplazamiento.setViewportView(panelPrincipal);

        getContentPane().add(barraDesplazamiento, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane barraDesplazamiento;
    public javax.swing.JButton btnActualizarEstudiante;
    public javax.swing.JButton btnActualizarTablaFormularioRegistro;
    public javax.swing.JButton btnActualizarView;
    public javax.swing.JButton btnBuscarConsulta;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiarEstudiante;
    public javax.swing.JButton btnRegistrarEstudiante;
    public javax.swing.JButton btnRegistrarView;
    public javax.swing.JComboBox<String> comboBoxGenero;
    public javax.swing.JComboBox<String> comboBoxTipoBusqueda;
    public javax.swing.JComboBox<String> comboBoxTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNumDoc;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTipoDoc;
    public javax.swing.JPanel panelBusqueda;
    public javax.swing.JPanel panelConsulta;
    public javax.swing.JPanel panelFormulario;
    public javax.swing.JPanel panelInicio;
    public javax.swing.JPanel panelListadoBusqueda;
    public javax.swing.JPanel panelListadoEstudiante;
    public javax.swing.JTabbedPane panelMenu;
    private javax.swing.JPanel panelPrincipal;
    public javax.swing.JPanel panelRegistroEstudiante;
    public javax.swing.JTable tableBusqueda;
    public javax.swing.JTable tableDatos;
    public javax.swing.JTextField textBusqueda;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNumDoc;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
